version: "2.1"
services: 
  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    command: "/venv/bin/python ./producer/producer/main.py"
    depends_on:
      message-broker:
        condition: service_healthy
    network_mode: host
    env_file: ./default.env

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    command: "/venv/bin/python ./consumer/consumer/main.py"
    depends_on:
      message-broker:
        condition: service_healthy
    network_mode: host
    env_file: ./default.env

  logger:
    privileged: true
    build:
      context: .
      dockerfile: ./logger/Dockerfile
    command: "/venv/bin/python ./logger/logger/main.py"
    depends_on:
      message-broker:
        condition: service_healthy
    network_mode: host
    env_file: ./default.env

  message-broker:
    container_name: message-broker
    image: rabbitmq:3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]

  redis:
    container_name: redis
    image: redis:6.2.1
    ports:
      - 6379:6379
