version: "3"
services: 
  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile
    volumes:
      - ./producer/:/usr/src/app/
      - ./common/:/usr/src/app/common
    command: "python producer.py"
    depends_on:
      - message-broker
    network_mode: host
    env_file: ./default.env

  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    volumes:
      - ./consumer/:/usr/src/app/
      - ./common/:/usr/src/app/common
    command: "python consumer.py"
    depends_on:
      - message-broker
    network_mode: host
    env_file: ./default.env

  message-broker:
    container_name: message-broker
    image: rabbitmq:3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
